flex1:
	flex prog1.l
	gcc lex.yy.c
	./a.out < input.txt > output.txt
flex2:
	flex prog2.l
	gcc lex.yy.c
	./a.out < input.txt > output.txt	
flex3:
	flex prog3.l
	gcc lex.yy.c
	./a.out < input.txt > output.txt
flex4:
	flex prog4.l
	gcc lex.yy.c
	./a.out < input.txt > output.txt				